import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Sidebar from "@/components/Sidebar/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="grid grid-cols-6 relative ">
        <div className="col-span-6  sticky top-0 bg-slate-50 z-10">
          <Navbar />
        </div>

        <div className="  col-span-1">
          <Sidebar />
        </div>
        <div className="col-span-5 ">{children}</div>
      </body>
    </html>
  );
}
